---
#
# Ansible managed
#
language: python

python:
  - "3.8"

services:
  - docker

env:
  global:
    namespace="robertdebock"
  matrix:
    - image="centos" tag="latest"
    - image="debian" tag="latest"
    - image="fedora" tag="31"
    - image="fedora" tag="latest"
    - image="opensuse" tag="latest"
    - image="ubuntu" tag="latest"

cache:
  - pip

install:
  - pip install --upgrade pip
  - pip install tox

script:
  - n=0 ; until [ "$n" = 3 ] ; do tox --parallel all && break ; n=$((n+1)) ; done

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
  slack: "T6wmIMoY2XYuSgSb8xh8yW2K5FU/TJHJy2aM1SP4xq+INRrmib9pUydgee1p+s1tkof6q0G7SoFlvbY3Uj5SLWQSpxry0KMq/vyruBjJv7uA0p1gY9ogQx6KJGKCql9uksi2gknihBoMxvWqq7savnqz+VfQHXeviW0nRR7kOk4n75MnpRWmhs7p9vd2D1X4veDKvhRXn+JtIL7ZMpvScBi3vAJCCzg9/ODl85+8aVPpPDDnA3jZbbpobLy2QO9B6mnzz8nix9Pg1uEKQL4FdBIvNxCc+lTdSG/WPnbnvu0LCB+an/2R6VwckRzdrz6kkuQJsDw2irIu9yLsXGvlLqm/z2ZSyFREiQHlal5h+F+3at3W/qA6rfq+2WbmgPSs41dDkib80NS2bi+r52Cd8jHKUr6lrEGHo+DT7pcjSm0tUWul4LIEV+xoNEAw3a6dFvZa1ZkR9U2uO3Snp67tKLqZxohbF2ZLnvOlmRDtGVDQhM9YGs+bD+4kEUxZhUEv5pO2kxq9TDIO8ERUznXE4UfLE38mSaBXRE+h2OiAOoox2QCKe+D9o6wL6HoMmMewCZfvgzXwsEA1WtB1bh5eUdKU8+bE3bNt1pR6bY2EEI56qqhH5dp68pDyYALRz/al0EzloC0n8lDFRQqeaKvBSlCGv8tpe7SdlPQX/lyBohA="
  email: false
