---
- name: test if revealmd_directory is set correctly
  assert:
    that:
      - revealmd_directory is defined
    quiet: yes

- name: test if revealmd_presentation is set correctly
  assert:
    that:
      - revealmd_presentation is defined
    quiet: yes

- name: test if revealmd_port is set correctly
  assert:
    that:
      - revealmd_port is defined
      - revealmd_port is number
      - revealmd_port > 0
      - revealmd_port < 65536
    quiet: yes

- name: test if revealmd_options is set correctly
  assert:
    that:
      - revealmd_options is defined
    quiet: yes
