---
# tasks file for revealmd
- name: install revealmd
  npm:
    name: reveal-md
    global: yes

- name: create directory
  file:
    path: "{{ directory }}"
    state: directory

- name: start revealmd
  shell: touch revealmd-started ; reveal-md --port {{ appport }} {{ options }} &
  args:
    chdir: "{{ directory }}"
    creates: revealmd-started
