---
# tasks file for ansible-role-revealmd
- name: install revealmd
  npm:
    name: reveal-md
    global: yes

- name: create directory
  file:
    path: "{{ directory }}"
    state: directory

- name: start revealmd
  shell: touch revealmd-started ; reveal-md --port {{ appport }} {{ options }} &
  async: 5
  poll: 0
  args:
    chdir: "{{ directory }}"
    creates: revealmd-started
  register: started
