---
# tasks file for revealmd
- name: install revealmd
  npm:
    name: reveal-md
    state: "{{ revealmd_package_state }}"
    global: yes
  register: revealmd_install_revealmd
  until: revealmd_install_revealmd
  retries: 3

- name: create directory
  file:
    path: "{{ revealmd_directory }}"
    state: directory

- name: place index.md default presentation
  copy:
    src: index.md
    dest: "{{ revealmd_directory }}/index.md"

- name: create revealmd service
  import_role:
    name: robertdebock.service

- name: start and enable revealmd
  service:
    name: revealmd
    state: started
    enabled: yes
