---
# tasks file for revealmd
- name: install revealmd
  npm:
    name: reveal-md
    global: yes

- name: start revealmd
  shell: reveal-md --port {{ port }} {{ options }} &
  async: 3
  poll: 0
  args:
    chdir: "{{ directory }}"
