---
# tasks file for revealmd
- name: install revealmd
  npm:
    name: reveal-md
    global: yes

- name: create directory
  file:
    path: "{{ directory }}"
    state: directory

- name: start revealmd
  shell: ( reveal-md --port {{ port }} {{ options }} & ) ; touch /tmp/revealmd-started
  async: 5
  poll: 0
  args:
    chdir: "{{ directory }}"
    creates: /tmp/revealmd-started
  register: started

- name: show variables
  debug:
    var: started
