---
# tasks file for revealmd
- name: install dependencies
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - git

- name: install revealmd
  npm:
    name: reveal-md
    state: present
    global: yes

- name: create directory
  file:
    path: "{{ revealmd_directory }}"
    state: directory

- name: start revealmd
  shell: touch revealmd-started ; reveal-md --port {{ revealmd_port }} {{ revealmd_options }} &
  args:
    chdir: "{{ revealmd_directory }}"
    creates: revealmd-started
