---
# tasks file for revealmd

- name: include assert.yml
  include_tasks: assert.yml
  run_once: yes

- name: install revealmd
  npm:
    name: reveal-md
    state: present
    global: yes

- name: create directory
  file:
    path: "{{ revealmd_directory }}"
    state: directory
    mode: "0755"

- name: place index.md default presentation
  copy:
    src: index.md
    dest: "{{ revealmd_directory }}/index.md"
    mode: "0644"

- name: create revealmd service
  import_role:
    name: robertdebock.service
  vars:
    service_list:
      - name: revealmd
        description: Markdown presentor
        start_command: "{{ revealmd_path }}/reveal-md --port {{ revealmd_port }} {{ revealmd_options | default(omit) }} {{ revealmd_presentation }}"
        working_directory: "{{ revealmd_directory }}"

- name: start and enable revealmd
  service:
    name: revealmd
    state: started
    enabled: yes
