---
# tasks file for revealmd
- name: install revealmd
  npm:
    name: reveal-md
    state: "{{ revealmd_package_state }}"
    global: yes
  register: revealmd_install_revealmd
  until: revealmd_install_revealmd
  retries: 3

- name: create directory
  file:
    path: "{{ revealmd_directory }}"
    state: directory

- name: start revealmd
  shell: "touch revealmd-started ; reveal-md --port {{ revealmd_port }} {{ revealmd_options }} &"
  args:
    chdir: "{{ revealmd_directory }}"
    creates: revealmd-started
