---
dependency:
  name: galaxy
  options:
    role-file: requirements.yml
driver:
  name: docker
lint:
  name: yamllint
platforms:
  - name: revealmd-archlinux
    image: base/archlinux
  - name: revealmd-alpine-3.6
    image: alpine:3.6
  - name: revealmd-alpine-3.7
    image: alpine:3.7
  - name: revealmd-centos-7
    image: centos:7
  - name: revealmd-fedora-26
    image: fedora:26
  - name: revealmd-fedora-27
    image: fedora:27
  - name: revealmd-opensuse-42.2
    image: opensuse:42.2
  - name: revealmd-opensuse-42.3
    image: opensuse:42.3
    # 16.04 LTS
  - name: revealmd-ubuntu-xenial
    image: ubuntu:xenial
    # 17.04
  - name: revealmd-ubuntu-artful
    image: ubuntu:artful
provisioner:
  name: ansible
  lint:
    name: ansible-lint
scenario:
  name: default
  test_sequence:
    - lint
    - destroy
    - dependency
    - syntax
    - create
    - prepare
    - converge
    - idempotence
    - check
    - side_effect
    - verify
    - destroy
verifier:
  name: goss
  lint:
    name: 'None'
