---
dependency:
  name: galaxy
  options:
    role-file: requirements.yml
lint:
  name: yamllint
driver:
  name: docker
platforms:
  - name: "instance-${TOX_ENVNAME:-default}"
    image: "${distribution:-robertdebock/docker-fedora-systemd:latest}"
    command: sh -c "while true ; do sleep 30 ; done"
    pre_build_image: yes
provisioner:
  name: ansible
  playbooks:
    prepare: prepare.yml
    converge: playbook.yml
  inventory:
    group_vars:
      all:
        ansible_python_interpreter: /usr/bin/python3
scenario:
  name: default
