---
- name: Converge
  hosts: all

  roles:
    - role: ansible-role-revealmd

  tasks:
    - name: test if port is open
      wait_for:
        host: "{{ inventory_hostname }}"
        port: "{{ port }}"
        delay: 5
        timeout: 30
